### ISSUE TITLE
Make lib a module with exports

### ISSUE THREAD

**Issue by Specy** [Specy-wot/SP-Code#1]
This lib currenlty works only on websites by importing with a link, might be good to add an export so it can be used with npm and webpack.

This also includes changing the README accordingly

**Comment by Megatank58** [comment]
Hello i would like to work on this

**Comment by tnb24** [comment]
#2

**Comment by oof2win2** [comment]
Can I claim it?

**Comment by Specy** [comment]
sure

**Comment by Specy** [comment]
i dont know if @tnb24 is still working on it as they made a PR some hours ago but then dropped it, wait for their answer

**Comment by tnb24** [comment]
Take it
